
// Auto-generated by AutoPilot on 16-08-2023 at 01:22:28


const express = require('express');
const router = express.Router();

// Route for getting books by Dan Brown
router.get('/custom', (req, res) => {
    res.json({
        books: ["The Da Vinci Code", "Angels & Demons", "The Lost Symbol", "Inferno"]
    });
});

module.exports = router;